platform :ios, '10.0'
use_frameworks!


target 'DouYuTV' do

pod 'Alamofire'
pod 'Kingfisher'
pod 'PullToRefreshKit', '~> 0.8.8'
pod 'SwiftyJSON', '~> 4.0'
pod 'IBAnimatable'
pod 'SwiftTheme'
pod 'FDFullscreenPopGesture'
pod 'RxCocoa'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'Moya'
pod 'Moya-SwiftyJSONMapper', '~> 3.0.0'
pod 'IQKeyboardManagerSwift'
pod 'ESPullToRefresh'
pod 'ObjectMapper', '~> 3.3.0'
end

